# Generated by Django 4.1 on 2022-08-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default="Idenify", max_length=10)),
                ("name", models.CharField(default="John Doe", max_length=255)),
                ("greeting", models.CharField(default="Hi!", max_length=255)),
                (
                    "main_designation",
                    models.CharField(default="Web Developer", max_length=255),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="documents/cv"),
                ),
                ("enable_services", models.BooleanField(default=True)),
                ("enable_pricing", models.BooleanField(default=True)),
                ("enable_testimonials", models.BooleanField(default=True)),
                ("enable_posts", models.BooleanField(default=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile"
                    ),
                ),
                ("enable_portfolio", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("to_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "host",
                    models.CharField(
                        choices=[("smtp.gmail.com", "gmail")],
                        default="smtp.gmail.com",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(choices=[(587, "gmail")], default=587),
                ),
            ],
            options={"verbose_name_plural": "Settings",},
        ),
    ]
